### ISSUE TITLE
Can't get my (or your) code to run in "Building a JavaScript Development Environment"

### ISSUE THREAD

**Issue by B-Enright** [coryhouse/codemash-2017#1]
Cory (or other), I was moving along well in your above course until the clip in the "Linting" module titled "Demo: ESLint Set Up". Upon running the code (npm run lint) at the 5:25 mark in the clip, I received a Terminal error (see .zip file).  At first I thought it was because I was running Node ver. 4.4 (for Windows), but I updated to ver. 6.94 (current) and still got the error (even with your code). The other thing I noticed is a Terminal complaint about not having a node_modules file. Your several previous modules didn't have a node_modules file, then it showed up in this one ("ESLint Set Up").  Screenshot and code .zip file below.

Any help would be appreciated. B-Enright - Pluralsight member.
![coryhousedemoeslintsetup1-10-17](https://cloud.githubusercontent.com/assets/2694343/21836234/4a80125e-d778-11e6-9277-a5f9477c19d6.JPG)

[jsCoryHouseDemo1-10-17.zip](https://github.com/coryhouse/codemash-2017/files/697966/jsCoryHouseDemo1-10-17.zip)

**Comment by coryhouse** [comment]
A few issues:
1. This repository isn't for my course. It's for a conference talk I'm giving soon.
2. You need to run `npm install`. That command will create a node_modules folder. This step is required for any course where I'm using Node, and I show it in the course.

I'm going to close this since it's not related to this repo, but feel free to post on the course discussion if your issue persists.
